pre-commit:
  parallel: true
  commands:
    eslint:
      glob: '*.{ts,tsx}'
      run: pnpm exec eslint --fix {staged_files}
      stage_fixed: true
    prettier:
      glob: '*.{ts,tsx,js,jsx,json,css,md}'
      run: pnpm exec prettier --write {staged_files}
      stage_fixed: true
